
    create table tb_verbs (
       id int8 generated by default as identity,
        infinitive varchar(30) not null,
        participle varchar(30) not null,
        past varchar(30) not null,
        portuguese varchar(100),
        type varchar(20) not null,
        primary key (id)
    );

    alter table if exists tb_verbs 
       add constraint UK_keu73i2drpex0qicq8ykuug59 unique (infinitive);

    alter table if exists tb_verbs 
       add constraint UK_8lgjeti248o20er3b0tir588d unique (participle);

    alter table if exists tb_verbs 
       add constraint UK_k6jdrnqwr4xceyeihew4cxsb3 unique (past);
